affinity: {}
applicationProdProperties:
  configmap:
    application-prod.properties: >-
      server.port=1001

      server.servlet.context-path=

      spring.mvc.view.prefix=/WEB-INF/jsp/

      spring.mvc.view.suffix=.jsp

      # Disable JPA

      spring.jpa.hibernate.ddl-auto=none

      spring.datasource.url=jdbc:mysql://my-release-mysql-primary.default.svc.cluster.local:3306/symplified

      spring.datasource.username=root

      spring.datasource.password=kalsym@123

      spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

      spring.jpa.properties.hibernate.dialect =
      org.hibernate.dialect.MySQLDialect

      spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

      spring.data.jpa.repositories.enabled=false

      # Persistance

      asset.file.path=/home/docker/Software/assets

      # value avaialble (true,false)

      asset.index.show=true

      #logging

      logging.config=logback.xml

      logging.level.root=WARN

      logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %-5level [%L] %msg%n
  volumeMount:
    - mountPath: /home/docker/Software/application-prod.properties
      name: asset-service-approd-vol
      subPath: application-prod.properties
  volumes:
    - configMap: null
      name: asset-service-approd-cm
applicationProperties:
  configmap:
    application.properties: |
      # Mininal config (please refer production application.properties values)
      spring.profiles.active=prod
      proj.name=asset-service
      build.version=@project.version@
  volumeMount:
    - mountPath: /home/docker/Software/application.properties
      name: asset-service-ap-vol
      subPath: application.properties
  volumes:
    - configMap:
        name: asset-service-ap-cm
      name: asset-service-ap-vol
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
fullnameOverride: ''
image:
  pullPolicy: Always
  repository: kalsym/asset-service
  tag: 1.0.0
imagePullSecrets:
  - name: kalsym-docker-hub
ingress:
  annotations: {}
  className: ''
  enabled: true
  hosts:
    - host: assets.symplified.it
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - assets.symplified.it
      secretName: secret-tls-it
logback:
  configmap:
    logback.xml: |
      <?xml version="1.0" encoding="UTF-8"?>
      <configuration>

          <property name="LOGS" value="/home/docker/Software/logs/symplified" />
          <property name="CDRS" value="/home/docker/Software/logs" />

          <property resource="application.properties" />

          <appender name="Console" class="ch.qos.logback.core.ConsoleAppender">
              <layout class="ch.qos.logback.classic.PatternLayout">
                  <Pattern>
                      %black(%d{ISO8601}) %highlight(%-5level) %yellow(%C{1.}): %msg%n%throwable
                  </Pattern>
              </layout>
          </appender>

          <appender name="APPLICATION" class="ch.qos.logback.core.rolling.RollingFileAppender">
              <file>${LOGS}/asset-service/asset-service.log</file>
              <append>true</append>
              <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                  <!-- rollover daily and when the file reaches 10 MegaBytes -->
                  <fileNamePattern>${LOGS}/asset-service/archived/asset-service-%d{yyyy-MM-dd}.%i.log
                  </fileNamePattern>
                  <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                      <maxFileSize>10MB</maxFileSize>
                  </timeBasedFileNamingAndTriggeringPolicy>
              </rollingPolicy>
              <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
                  <charset>UTF-8</charset>
                  <layout class="ch.qos.logback.classic.PatternLayout">
                      <Pattern>%d %p %M %L [%t] - %m%n</Pattern>
                  </layout>
              </encoder>
          </appender>

          <appender name="CDR" class="ch.qos.logback.core.rolling.RollingFileAppender">
              <file>${CDRS}/asset-service-cdr.csv</file>
              <append>true</append>
              <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                  <!-- rollover daily and when the file reaches 10 MegaBytes -->
                  <fileNamePattern>${CDRS}/asset-service/cdrs/cdr-%d{yyyy-MM-dd}.%i.csv
                  </fileNamePattern>
                  <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                      <maxFileSize>10MB</maxFileSize>
                  </timeBasedFileNamingAndTriggeringPolicy>
              </rollingPolicy>
              <encoder class="ch.qos.logback.core.encoder.LayoutWrappingEncoder">
                  <charset>UTF-8</charset>
                  <layout class="ch.qos.logback.classic.PatternLayout">
                      <Pattern>%date{dd:MMM:yyyy;HH:mm:ss.SSS},%m%n</Pattern>
                  </layout>
              </encoder>
          </appender>

          <!-- LOG everything at INFO level -->
          <root level="INFO">
              <appender-ref ref="APPLICATION" />
          </root>

          <logger name="cdr" level="DEBUG" additivity="false">
              <appender-ref ref="CDR" />
          </logger>

          <!-- LOG "com.baeldung*" at TRACE level -->
          <!-- <logger name="application" level="DEBUG" additivity="true">
              <appender-ref ref="APPLICATION" />
          </logger> -->

      </configuration>
  volumeMount:
    - mountPath: /home/docker/Software/logback.xml
      name: asset-service-lgb-vol
      subPath: logback.xml
  volumes:
    - configMap:
        name: asset-service-lgb-cm
      name: asset-service-lgb-vol
nameOverride: ''
nodeSelector: {}
podAnnotations: {}
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 1001
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: false
  name: ''
tolerations: []